#!/bin/bash
title Compiling Doom
echo on
cls

emcc src/i_main.c             ^
     src/i_system.c           ^
     src/m_argv.c             ^
     src/m_misc.c             ^
     src/aes_prng.c           ^
     src/d_event.c            ^
     src/d_iwad.c             ^
     src/d_loop.c             ^
     src/d_mode.c             ^
     src/deh_str.c            ^
     src/gusconf.c            ^
     src/i_cdmus.c            ^
     src/i_endoom.c           ^
     src/i_input.c            ^
     src/i_joystick.c         ^
     src/i_midipipe.c         ^
     opl/opl.c                ^
     opl/opl_linux.c          ^
     opl/opl_obsd.c           ^
     opl/opl_queue.c          ^
     opl/opl_sdl.c            ^
     opl/opl_timer.c          ^
     opl/opl_win32.c          ^
     opl/ioperm_sys.c         ^
     opl/opl3.c               ^
     src/i_oplmusic.c         ^
     src/i_pcsound.c          ^
     src/i_sdlmusic.c         ^
     src/i_sdlsound.c         ^
     src/i_sound.c            ^
     src/i_timer.c            ^
     src/i_video.c            ^
     src/i_videohr.c          ^
     src/midifile.c           ^
     src/mus2mid.c            ^
     src/m_bbox.c             ^
     src/m_cheat.c            ^
     src/m_config.c           ^
     src/m_controls.c         ^
     src/m_fixed.c            ^
     src/sha1.c               ^
     src/memio.c              ^
     src/tables.c             ^
     src/v_diskicon.c         ^
     src/v_video.c            ^
     src/w_checksum.c         ^
     src/w_main.c             ^
     src/w_wad.c              ^
     src/w_file.c             ^
     src/w_file_stdc.c        ^
     src/w_file_posix.c       ^
     src/w_file_win32.c       ^
     src/w_merge.c            ^
     src/z_zone.c             ^
     src/deh_io.c             ^
     src/deh_main.c           ^
     src/deh_mapping.c        ^
     src/deh_text.c           ^
     src/doom/am_map.c        ^
     src/doom/deh_ammo.c      ^
     src/doom/deh_bexstr.c    ^
     src/doom/deh_cheat.c     ^
     src/doom/deh_doom.c      ^
     src/doom/deh_frame.c     ^
     src/doom/deh_misc.c      ^
     src/doom/deh_ptr.c       ^
     src/doom/deh_sound.c     ^
     src/doom/deh_thing.c     ^
     src/doom/deh_weapon.c    ^
     src/doom/d_items.c       ^
     src/doom/d_main.c        ^
     src/doom/d_net.c         ^
     src/doom/doomdef.c       ^
     src/doom/doomstat.c      ^
     src/doom/dstrings.c      ^
     src/doom/f_finale.c      ^
     src/doom/f_wipe.c        ^
     src/doom/g_game.c        ^
     src/doom/hu_lib.c        ^
     src/doom/hu_stuff.c      ^
     src/doom/info.c          ^
     src/doom/m_menu.c        ^
     src/doom/m_random.c      ^
     src/doom/p_ceilng.c      ^
     src/doom/p_doors.c       ^
     src/doom/p_enemy.c       ^
     src/doom/p_floor.c       ^
     src/doom/p_inter.c       ^
     src/doom/p_lights.c      ^
     src/doom/p_map.c         ^
     src/doom/p_maputl.c      ^
     src/doom/p_mobj.c        ^
     src/doom/p_plats.c       ^
     src/doom/p_pspr.c        ^
     src/doom/p_saveg.c       ^
     src/doom/p_setup.c       ^
     src/doom/p_sight.c       ^
     src/doom/p_spec.c        ^
     src/doom/p_switch.c      ^
     src/doom/p_telept.c      ^
     src/doom/p_tick.c        ^
     src/doom/p_user.c        ^
     src/doom/r_bsp.c         ^
     src/doom/r_data.c        ^
     src/doom/r_draw.c        ^
     src/doom/r_main.c        ^
     src/doom/r_plane.c       ^
     src/doom/r_segs.c        ^
     src/doom/r_sky.c         ^
     src/doom/r_things.c      ^
     src/doom/s_sound.c       ^
     src/doom/sounds.c        ^
     src/doom/statdump.c      ^
     src/doom/st_lib.c        ^
     src/doom/st_stuff.c      ^
     src/doom/wi_stuff.c      ^
     -s USE_SDL=2             ^
     -s ALLOW_MEMORY_GROWTH=1 ^
     -s ASSERTIONS=1          ^
     -o doom.h                ^
     --embed-file doom.wad
